# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jAoOrSrEPUxJvnIl3cQJcD6qOzoTF8W8
"""

#!pip install streamlit

import streamlit as st
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

st.set_page_config(page_title="Credit Risk Prediction", layout="wide")
st.title("💳 German Credit Risk Classifier")

# Load dataset
@st.cache_data
def load_data():
    columns = [
        "Status", "Duration", "CreditHistory", "Purpose", "CreditAmount",
        "Savings", "EmploymentSince", "InstallmentRate", "PersonalStatusSex",
        "OtherDebtors", "ResidenceSince", "Property", "Age", "OtherInstallmentPlans",
        "Housing", "NumberCredits", "Job", "PeopleLiable", "Telephone", "ForeignWorker", "Target"
    ]
    df = pd.read_csv("german.data", sep='\s+', header=None, names=columns)
    df['Target'] = df['Target'].replace({1: 1, 2: 0})

    le = LabelEncoder()
    for col in df.select_dtypes(include=['object']).columns:
        df[col] = le.fit_transform(df[col])
    return df

# Load and prepare model
df = load_data()
X = df.drop('Target', axis=1)
y = df['Target']
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

# Sidebar form for prediction input
st.sidebar.header("📋 Enter Applicant Information")

def user_input_features():
    data = {
        "Status": st.sidebar.selectbox("Status", options=sorted(df["Status"].unique())),
        "Duration": st.sidebar.slider("Duration (months)", 4, 72, 24),
        "CreditHistory": st.sidebar.selectbox("Credit History", sorted(df["CreditHistory"].unique())),
        "Purpose": st.sidebar.selectbox("Purpose", sorted(df["Purpose"].unique())),
        "CreditAmount": st.sidebar.slider("Credit Amount", 250, 20000, 1000),
        "Savings": st.sidebar.selectbox("Savings", sorted(df["Savings"].unique())),
        "EmploymentSince": st.sidebar.selectbox("Employment Since", sorted(df["EmploymentSince"].unique())),
        "InstallmentRate": st.sidebar.slider("Installment Rate", 1, 4, 2),
        "PersonalStatusSex": st.sidebar.selectbox("Personal Status/Sex", sorted(df["PersonalStatusSex"].unique())),
        "OtherDebtors": st.sidebar.selectbox("Other Debtors", sorted(df["OtherDebtors"].unique())),
        "ResidenceSince": st.sidebar.slider("Residence Since", 1, 4, 2),
        "Property": st.sidebar.selectbox("Property", sorted(df["Property"].unique())),
        "Age": st.sidebar.slider("Age", 18, 75, 35),
        "OtherInstallmentPlans": st.sidebar.selectbox("Other Installment Plans", sorted(df["OtherInstallmentPlans"].unique())),
        "Housing": st.sidebar.selectbox("Housing", sorted(df["Housing"].unique())),
        "NumberCredits": st.sidebar.slider("Number of Credits", 1, 4, 2),
        "Job": st.sidebar.selectbox("Job", sorted(df["Job"].unique())),
        "PeopleLiable": st.sidebar.slider("People Liable", 1, 2, 1),
        "Telephone": st.sidebar.selectbox("Telephone", sorted(df["Telephone"].unique())),
        "ForeignWorker": st.sidebar.selectbox("Foreign Worker", sorted(df["ForeignWorker"].unique()))
    }
    return pd.DataFrame(data, index=[0])

input_df = user_input_features()

# Prediction Section
st.subheader("🧠 Credit Risk Prediction")
if st.sidebar.button("Predict Credit Risk"):
    prediction = rf.predict(input_df)[0]
    prediction_proba = rf.predict_proba(input_df)[0]

    if prediction == 1:
        st.success(f"✅ Prediction: Good Credit Risk (Confidence: {prediction_proba[1]*100:.2f}%)")
    else:
        st.error(f"❌ Prediction: Bad Credit Risk (Confidence: {prediction_proba[0]*100:.2f}%)")

# Display model performance
st.subheader("📊 Model Evaluation on Test Data")
y_pred = rf.predict(X_test)
st.write("Accuracy:", accuracy_score(y_test, y_pred))
st.text("Classification Report")
st.text(classification_report(y_test, y_pred))

# Feature Importance
st.subheader("🔍 Feature Importance")
importances = rf.feature_importances_
features = X.columns
indices = np.argsort(importances)[::-1]

fig, ax = plt.subplots(figsize=(10, 5))
sns.barplot(x=importances[indices], y=features[indices], ax=ax)
st.pyplot(fig)

